### PR TITLE
Disable buttons that are not password protected, since the site is no…

### PR DESCRIPTION
**Pull request by alexbfree**
…w linked from the MICO public site

### CODE REVIEW

**Comment by alexbfree** [comment]
BTW @marten if you have a better idea like adding a password onto these links or something, we could do that. but probably let's disable as a first step as the demo is already linked to on the new MICO site.

**Comment by alexbfree** [comment]
Thanks @marten . I can't remember, does this auto deploy or do we need to do something?

**Comment by marten** [comment]
We need to run the "Build Legacy Apps AMI" task in Jenkins, but I've kicked it off.

**Comment by alexbfree** [comment]
Great, thanks

**Pull request merged**
